### ISSUE TITLE
Push button issue

### ISSUE THREAD

**Issue by ZKullai** [iltis42/XCFlarmView#1]
The push button does not recognizes the long press at startup and in menu. Furthermore by press and hold at startup the device does not boot up.

**Comment by iltis42** [comment]
The push button is connected to the bootstrap pin of ESP32 for factory flashing of the firmware, and must not be pressed at power on startup, the device will enter programming mode via internal USB.   
In startup phase, when the init splash screen appeares, the push button operates as described on screen, if pressed the firmware update via WiFi will be launched. No long press either at that time.
The long press is processed after boot phase to enter setup menu. The the menu the long press works like a double click or <enter> to trigger action to confirm a new setting or return back from setup into normal operation. 
This explanation should resolve this issue.
