### ISSUE TITLE
Optional waning on new target

### ISSUE THREAD

**Issue by HoeckDK** [iltis42/XCFlarmView#4]
Hi

I just flew the danish nationals. 70 planes participating. 

It seems there is an audio warning every time a new target is observed. 

I would like to have a setting for that. I ended up disabling audio altogether. Probably not ideal but the constant beeps from targets that were not a safety factor was too distracting. 

I also observed a few unexpected restarts of the display. 

Thanks.

**Comment by iltis42** [comment]
Check out the latest SW, the beep (hysteresis) has been optimized (1) and one possible cause of restart (bug) is fixed (2). 

https://github.com/iltis42/XCFlarmView/releases/tag/24.0513

1) https://github.com/iltis42/XCFlarmView/commit/e327ac9dbf3bf5a23c3f7f182b7eaa8f179ce8bd
2) https://github.com/iltis42/XCFlarmView/commit/35c202d17b3b1c8afb8b1dc895f555e0ec39dfce

If you experience or suspect restart's, please check also for a core file in SW update web-UI, and attach this here.
