### ISSUE TITLE
Update of Flarmnet file

### ISSUE THREAD

**Issue by Bumpff** [iltis42/XCFlarmView#8]
Can the Flarmnet file be made a separate update to the firmware?  The Flarmnet file is published daily and there may be changes in our locality that we want available on the display ASAP, so don't want to wait for next firrnware.  Perhaps allow use of one of the stanard published flarmnet file formats.

**Comment by iltis42** [comment]
ATM there is not any option as flarmnet file is needed as binary part of the firmware, so we need to rebuild the firmware. It can't be included as an ASCII file, this took too much resources. A new firmware can be triggered at any time by yourself e.g. cloning the project and start a build.
Here is a recent build i have triggered for you just now for the small 1.4 inch device with latest flarmnet: 
https://github.com/iltis42/XCFlarmView/actions/runs/11883029826/artifacts/2198986526

**Comment by MuenchowT** [comment]
Well, I would be interested also in a more current flarmnet file. The "solution" iltis42 suggested is obviously not for "non developers". I have done a clone/compile last year and it took me several hours to get the device running again after that. At least, there should be a short HowTo-compile-and-load in the docs. Another option would be an automatic weekly compile by the developers....
